dist: trusty
os: linux
language: node_js
node_js:
  - "8"
cache:
directories:
  - "node_modules"
before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono wine1.8 gcc-multilib g++-multilib
script: 
  - npm install -g bower
  - npm update -g npm
  - bower install
  - npm run package-linux
  - npm run package-mac
  - npm run package-windows
before_deploy:
  - cd build
  - bash ../script/zip.sh
  - export RELEASE_PKG_FILE=$(ls *.zip)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  - provider: releases
    api_key:
      secure: ad/bSbnHNx5Xu5A6EmSjn0vvyfINP9YbD4fjNhmdTsfFc9VfBEr6dN/t+wAwdn1BhiMoLjmoECc2B2KUUCX7ddUN4sj5OBx9mkc+kMSwJ8Bx17A/5vD1KBJwuycY7iYEpPo/BkMbMwB+NcKTGSCQ2iTmhRWCbAAoAJKwEufVRaMEW54mocIBnGFXxzBdR23LYOL31Vn0ZWUg40oRiAcjbX+F8Fia4cEjMPL1rmmeoBFgV/iUnyHaof3/9fr5ky6ML1Gth/Qz+/wj8e42ueKd0Nm0sy7ATyAAi0UGM4Q9Tl1hKaChHnIcReuWwoKVrpqSAVRSLJINDQ0EKnpqmPuoj0LE4m/PbBJFRmgg/D601seebo7r1cmTNbB778VayYNL7vE6SslR/4LivgnrYC479XVKrsWu+9VmcYqctl6AQ5VzjGZoK/YKV5uV2eoK3t1qymjC9FZx/6uVk4RxzPN0iFHlki6bSHU2k64rSO0PGSIRZ+pE11rlfHFruiuN2JrgGwVUkY5zDlK1ZiqBAnXWeS0NQYRiyI/oNoY46artQkuqN9SPcj/aN0y53XHIOG2Ixp5lzlqrRihHeh+RkHIYOpxxQLxHDGPymgIqv5AmUi+g+7LVaufP2dZWhEoiPqxaucUH8+tRmybzs11maEPSk60mH06upBAjnRvqfbDhJRc=
    skip_cleanup: true
    file_glob: true
    file: "*.zip"
    on:
      branch: master
  - provider: releases
    api_key:
      secure: ad/bSbnHNx5Xu5A6EmSjn0vvyfINP9YbD4fjNhmdTsfFc9VfBEr6dN/t+wAwdn1BhiMoLjmoECc2B2KUUCX7ddUN4sj5OBx9mkc+kMSwJ8Bx17A/5vD1KBJwuycY7iYEpPo/BkMbMwB+NcKTGSCQ2iTmhRWCbAAoAJKwEufVRaMEW54mocIBnGFXxzBdR23LYOL31Vn0ZWUg40oRiAcjbX+F8Fia4cEjMPL1rmmeoBFgV/iUnyHaof3/9fr5ky6ML1Gth/Qz+/wj8e42ueKd0Nm0sy7ATyAAi0UGM4Q9Tl1hKaChHnIcReuWwoKVrpqSAVRSLJINDQ0EKnpqmPuoj0LE4m/PbBJFRmgg/D601seebo7r1cmTNbB778VayYNL7vE6SslR/4LivgnrYC479XVKrsWu+9VmcYqctl6AQ5VzjGZoK/YKV5uV2eoK3t1qymjC9FZx/6uVk4RxzPN0iFHlki6bSHU2k64rSO0PGSIRZ+pE11rlfHFruiuN2JrgGwVUkY5zDlK1ZiqBAnXWeS0NQYRiyI/oNoY46artQkuqN9SPcj/aN0y53XHIOG2Ixp5lzlqrRihHeh+RkHIYOpxxQLxHDGPymgIqv5AmUi+g+7LVaufP2dZWhEoiPqxaucUH8+tRmybzs11maEPSk60mH06upBAjnRvqfbDhJRc=
    skip_cleanup: true
    file_glob: true
    file: "*.zip"
    on:
      tags: true